"use client";
import Image from "next/image";
import { cases, faq, practices, principles, team } from "../data/site";

export function Header({ menuOpen, onMenu }: { menuOpen: boolean; onMenu: () => void }) {
  return <header className="site-header"><a className="brand" href="#top">VERITAS<span>.</span></a><nav className="desktop-nav"><a href="#about">О компании</a><a href="#practices">Практики</a><a href="#team">Команда</a><a href="#approach">Подход</a><a href="#cases">Кейсы</a><a href="#contacts">Контакты</a></nav><a className="button button-dark header-cta" href="#contacts">Обсудить задачу <span>↗</span></a><button className="menu-toggle" aria-label={menuOpen ? "Закрыть меню" : "Открыть меню"} aria-expanded={menuOpen} onClick={onMenu}><i></i><i></i></button></header>;
}

export function MobileMenu({ open }: { open: boolean }) { return <div className={`mobile-menu${open ? " mobile-menu-open" : ""}`}><a href="#about">О компании</a><a href="#practices">Практики</a><a href="#team">Команда</a><a href="#approach">Подход</a><a href="#cases">Кейсы</a><a href="#contacts">Контакты</a><a className="button button-light" href="#contacts">Обсудить задачу <span>↗</span></a></div>; }

export function Hero() { return <section className="hero section-dark" id="top"><div className="hero-content reveal"><p className="eyebrow">ЮРИДИЧЕСКАЯ КОМПАНИЯ ДЛЯ БИЗНЕСА</p><h1>Право, которое<br /><em>работает</em> на ваш бизнес.</h1><p className="hero-copy">Защищаем интересы компаний, сопровождаем сделки и помогаем принимать юридически выверенные решения без лишней сложности.</p><div className="hero-actions"><a className="button button-light" href="#contacts">Обсудить задачу <span>↗</span></a><a className="text-link" href="#practices">Наши практики <span>↓</span></a></div></div><div className="hero-image"><Image src="/images/veritas-hero.png" alt="Современная деловая архитектура" fill priority sizes="(max-width: 760px) 100vw, 55vw" /></div><div className="hero-meta"><span>Москва / Россия</span><span>Работаем с 2010 года</span></div></section>; }

export function About() { return <section className="about section-light" id="about"><div className="section-label">01 / О КОМПАНИИ</div><div className="about-grid"><h2 className="reveal">Юридическая экспертиза<br /><span>без лишнего шума.</span></h2><div className="about-body reveal"><p>VERITAS работает с предпринимателями и компаниями, которым важно не просто решить юридический вопрос, а понимать последствия каждого решения.</p><a className="text-link text-link-dark" href="#contacts">Узнать больше <span>↗</span></a></div></div><div className="stats">{[["15+", "лет практики"], ["120+", "завершённых проектов"], ["40+", "компаний на сопровождении"]].map(([value, label]) => <div className="stat reveal" key={label}><strong>{value}</strong><span>{label}</span></div>)}</div></section>; }

export function Practices() { return <section className="practices section-light" id="practices"><div className="section-label">02 / ПРАКТИКИ</div><div className="section-heading"><h2>Чем мы<br /><span>занимаемся</span></h2><p>Фокусируемся на задачах, где точность решения определяет устойчивость бизнеса.</p></div><div className="practice-grid">{practices.map(([num, title, desc]) => <article className="practice-card reveal" key={num}><span className="card-num">{num}</span><div><h3>{title}</h3><p>{desc}</p></div><span className="card-arrow">↗</span></article>)}</div></section>; }

export function Approach() { return <section className="approach section-dark" id="approach"><div className="section-label label-muted">03 / ПОДХОД</div><div className="approach-grid"><h2 className="reveal">Думаем не только<br />о праве, но и <em>о результате.</em></h2><div className="principles">{principles.map((item, i) => <div className="principle reveal" key={item}><span>0{i + 1}</span><h3>{item}</h3><i>↗</i></div>)}</div></div></section>; }

export function Team() { return <section className="team section-light" id="team"><div className="section-label">04 / КОМАНДА</div><div className="section-heading"><h2>Люди, которые<br /><span>отвечают за результат</span></h2><p>Опыт, внимательность к деталям и ясный язык — то, что мы приносим в каждую задачу.</p></div><div className="team-grid">{team.map(([name, role, spec, image]) => <article className="person reveal" key={name}><div className="person-image"><Image src={image} alt={name} fill priority sizes="(max-width: 760px) 100vw, 25vw" /></div><div className="person-info"><h3>{name}</h3><p>{role}</p><span>{spec}</span></div></article>)}</div></section>; }

export function Cases() { return <section className="cases section-light" id="cases"><div className="section-label">05 / КЕЙСЫ</div><div className="section-heading"><h2>Практика в<br /><span>реальных задачах</span></h2><p>Мы помогаем принимать решения, которые выдерживают проверку временем и обстоятельствами.</p></div><div className="case-list">{cases.map(([num, title, task, approach]) => <article className="case reveal" key={num}><span className="case-num">{num}</span><h3>{title}</h3><div className="case-detail"><p><b>Задача</b>{task}</p><p><b>Подход</b>{approach}</p><p><b>Результат</b>Решение, встроенное в задачи и ритм бизнеса.</p></div><span className="case-arrow">↗</span></article>)}</div></section>; }

export function FAQ() { return <section className="faq section-light"><div className="section-label">06 / FAQ</div><div className="faq-grid"><h2 className="reveal">Частые<br /><span>вопросы</span></h2><div className="faq-list">{faq.map(([question, answer]) => <details className="faq-item reveal" key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></div></section>; }

export function Contact() { return <section className="contact section-dark" id="contacts"><div className="section-label label-muted">07 / КОНТАКТЫ</div><div className="contact-inner reveal"><p className="eyebrow">ОТКРЫТЫ К НОВЫМ ЗАДАЧАМ</p><h2>Есть юридическая задача?<br /><em>Давайте разберём её.</em></h2><p>Опишите ситуацию в нескольких предложениях — мы свяжемся с вами и предложим следующий шаг.</p><a className="button button-light" href="mailto:hello@veritas-law.ru">Обсудить задачу <span>↗</span></a></div></section>; }

export function Footer() { return <footer className="footer section-dark"><div className="footer-top"><a className="brand brand-footer" href="#top">VERITAS<span>.</span></a><p>Право, которое работает<br />на ваш бизнес.</p><div className="footer-links"><a href="#about">О компании</a><a href="#practices">Практики</a><a href="#team">Команда</a><a href="#cases">Кейсы</a><a href="#contacts">Контакты</a></div><div className="footer-contact"><span>Москва</span><a href="tel:+79990000000">+7 (999) 000-00-00</a><a href="mailto:hello@veritas-law.ru">hello@veritas-law.ru</a></div></div><div className="footer-bottom"><span>© 2026 VERITAS</span><span>Юридическая компания для бизнеса</span><a href="#top">Наверх ↑</a></div></footer>; }
